### ISSUE TITLE
Support for setting input variables

### ISSUE THREAD

**Issue by bernhard-thiele** [OpenModelica/OMFMISimulator#55]
The `oms_setReal(..)` API function works only for parameters. There is no direct support for setting input variables. The question is how to change the API for supporting inputs.

I made one attempt in which I introduced a `oms_setRealParameter()` function and redefined `oms_setReal()`:

https://github.com/bernhard-thiele/OMSimulator/commit/a506b142361f8425a47cb91e1a526bea5c701c3a

However, maybe it is preferable to have instead a dedicated `oms_setRealInput()` function? How should one handle external inputs?

**Comment by lochel** [comment]
We could add a function to set constant values to inputs. That could be used to set input values from external resources within a scripting environment.

**Comment by bernhard-thiele** [comment]
ok, what are your thoughts about how this function should be named and about its signature? Or should we rather extend `oms_setReal` so that both, parameters and input variables can be set with the same function?

**Comment by lochel** [comment]
Sounds like a good idea to use `oms_setReal` for both parameters and inputs.
