### ISSUE TITLE
Logfile output not configurable

### ISSUE THREAD

**Issue by sjoelund** [OpenModelica/OMFMISimulator#74]
If you run multiple instances of the simulator in parallel from the same directory, they will all output to the same log-file. I would have expected the default to print to stdout (there is no indication of anything happening right now). I propose that there is a command-line flag to choose log-file and possibly also to output to stdout.

**Comment by lochel** [comment]
Yes, that has to be changed somehow. I am thinking about dumping always to stdout instead of file. Would that solve the issue?

**Comment by sjoelund** [comment]
It would since it's easy to redirect output anyway (and it's just changing one line or something like that to make the existing stream reference cout). But only for the stand-aloine tool. In library mode, you want a configurable log-file (or possibly even a stream sent as input).

**Comment by lochel** [comment]
It is now possible to specify a logfile. If no filename is specified, then the logging information is dumped to stdout/stderr.
The logfile can be specified using `-logFile` or `-l` from CLI and with `setLogFile("<filename>")` from lua scripts.
